### ISSUE TITLE
build: Microsoft Visual Studio compilation support

### ISSUE THREAD

**Issue by JanSimek** [vayerx/shadowgrounds#12]
I fixed the Windows build with MSVC. Unfortunately, I am at a loss on how to make a proper pull request which contains only these two commits and not the whole fork:

https://github.com/JanSimek/shadowgrounds/commit/5c545722603c8d9448100ea6d78f59ee82147f4f
https://github.com/JanSimek/shadowgrounds/commit/0ce6c72db0071947fee72b87e41f2893bfbab98b

I haven't done any playtesting yet, but it compiles fine on Windows 7 and OS X 10.9

**Comment by vayerx** [comment]
If there are one or two commits, I can cherry-pick them manually. But if you would like to make a pull request, you should create a new branch from the latest fetched commit in target branch of my repository and cherry-pick necessary commits to that branch. Then you'll be able to create pull request.

**Comment by vayerx** [comment]
I've merged those commits. Thanks for patches!
I made small changes in data-paths logic -- please could you check if it works for Windows.

**Comment by JanSimek** [comment]
It's a little bit inconvenient, because this way you have to specify these data path variables on the command line and you can't use cmake-gui, because those variables are not set. Most people use cmake-gui to configure CMake-based projects.
