### ISSUE TITLE
System mouse cursor showed ingame

### ISSUE THREAD

**Issue by montaropdf** [vayerx/shadowgrounds#21]
In both survivor and shadowgrounds, the mouse cursor of the graphical environment is visible. This could explain the problem regarding le limitation of turning the character in survivor.

System information:
Laptop Asus K73SJ
CPU: Intel core i7
RAM: 8 Go
OS: Fedora 21 64 bits
Graphical Environment: KDE

**Comment by vayerx** [comment]
"Final release" option was disabled by default. It prevented the game from grabbing cursor. Make a clean build with the latest commit or run cmake with `-DFINAL_RELEASE_BUILD=ON`.
